#!/bin/bash
IpAddress=`hostname -I`
VarStart=`echo "$IpAddress"` | cut -c 1
VarEnd=${IpAddress##$VarStart*.}
FinalIpAddress=${IpAddress%$VarEnd}
for i in {1..255}; do
	IPUpdate="$FinalIpAddress$i"
	if ping -c 1 -W 1 "$IPUpdate" >/dev/null 2>&1; then
		echo "$IPUpdate is alive"
		host=`host $IPUpdate | cut -d' ' -f5`
		if [ $host = "3(NXDOMAIN)" ]; then
			echo "host: none"
		else
			echo "host: $host"
		fi
		File_MacAddress=`grep $IPUpdate /proc/net/arp`
		MacAddress=`echo $File_MacAddress | cut -d' ' -f4`
		echo "Mac Address: $MacAddress"
		if nc -z -w 1 $IPUpdate 22; then
			echo "ssh is open"
		else
			echo "ssh is closed"
		fi
		if nc -z -w 1 $IPUpdate 80; then
			echo "http is open"
		else
			echo "http is closed"
		fi
	else
		echo "$IPUpdate is dead"
	fi
done

exit 0
